### ISSUE TITLE
"An error occurred..."

### ISSUE THREAD

**Issue by lethesdomoi** [johannes-schliephake/nextcloud-passwords-ios#141]
After logging in to my Nextcloud account the Passwords iOS app simply says: "An error occurred..."

This has been so for at least a couple of months. Other methods of accessing Nextcloud Passwords (for example, the Chrome extension) still work. I have done a clean reinstalled of the iOS app and the problem persists.

I am using version 2.3 of the iOS app. On the server, Nextcloud Passwords is at version 2021.10.20.

**Comment by johannes-schliephake** [comment]
Hey, really sorry to hear that!

Past versions of the app sometimes had this behaviour when being offline, but this shouldn't be a general issue.

Is there anything special about your Nextcloud setup? For example LDAP, self-signed certificate, reverse proxy, installation into a subfolder of your domain?

**Comment by rpcurley324** [comment]
Hello,

I can confirm that the latest update of this app broke it. I have used this app as my main company password manager since day one. After updating the app 2 days ago it has this "An error occurred..." message no matter what I do. I noticed that there was an update for it this morning and that did not change the behavior.

If you are working on this already, ignore this comment. I just wanted you to know that this is happening to others out here.

Thank you for all your hard work.

**Comment by johannes-schliephake** [comment]
Interesting. If I understand correctly the error message started to appear after you updated the server side app. Also v2.4 removed a lot of error cases. The error screen now will only appear if the server sent a faulty response. This leads me to believe that the problem is on the server side.

I wasn't able to reproduce anything yet, so I need more details. Which iOS version do you run? Is there anything special or non-standard about your Nextcloud server? Are the issues appearing only on this specific account or with every account of the Nextcloud instance?
