### ISSUE TITLE
iPad version

### ISSUE THREAD

**Issue by JabelsBS** [johannes-schliephake/nextcloud-passwords-ios#16]
Hey, i would love to run your client on a iPad Pro.
I have testflight installed, so i can test any app if needed.

**Comment by johannes-schliephake** [comment]
I have enabled iPad support and optimized all layouts as good as possible. SwiftUI (which this app is based on) is currently pretty incomplete when it comes to iPad layout. Everything should work as expected, but some views are just blown up phone layouts. We'll have to wait for future releases of SwiftUI for nicer solutions.

I won't release the update on TestFlight because it also contains a handful of important bugfixes and I want to get those out as fast as possible. But I would still appreciate your honest feedback on the layouts as this is only tested in a simulator with mouse input :)
