### ISSUE TITLE
iOS App not available in my country

### ISSUE THREAD

**Issue by Luth1ng** [johannes-schliephake/nextcloud-passwords-ios#209]
Hello,

I cannot figure where I should ask for this, sorry if it's inappropriate.

I was living in Metropolitan France where I first used the Passwords Addon and the Passwords iOS App.
Then, I moved to Reunion Island which is an oversea french territory ("La Réunion" in french), but considered as a whole country in the Apple Appstore store.

I cannot download the Passwords iOS App within Reunion Island/ with an Apple Account registered in Reunion Island.
The error message is :

> **App Not Available**
> This app is currently not available in your country or region.

I know the workaround is to change the country of my iCloud account, but it will be great to just add it to our store.

Will it be possible to add the Passwords iOS App in Reunion Island Appstore store?

**Comment by johannes-schliephake** [comment]
Of course you may ask! :)

Since bringing the app back to the French App Store it is actually enabled for every region the App Store supports. I couldn't find Reunion Islands in the list of available regions. Here it's also not listed: https://www.apple.com/ios/feature-availability/#app-store-apps.

Can you download other apps with the account registered in Reunion Islands?

**Comment by Luth1ng** [comment]
I just checked yesterday, and the app is now available on our store.
I don't know if Apple made a change with the Store to be identical too the french one, but it is now available for us.
It wasn't possible two weeks ago, for sure.

Anyway, nice job, please keep doing this :)

**Comment by johannes-schliephake** [comment]
Awesome, happy to hear that! :)
