### ISSUE TITLE
Tip outside the app store possible?

### ISSUE THREAD

**Issue by flo-mic** [johannes-schliephake/nextcloud-passwords-ios#266]
Hi @johannes-schliephake, firts of all many thanks for this app. I really like it and use it almost daily. I would like to send you some tip to say thanks for the great app. I see there is a possibility to send this within the app over apples store. I guess in this case 30% of the tip will be send to apple and only 70% arrive on your side or?

is there any possibility to send you a tip outside of apples store to make sure you get all the money as you are spending your free time to maintain this app and not apple. Maybe you can add some other possibilities in the project description?

Thanks again for this great app!

**Comment by johannes-schliephake** [comment]
Hey, thanks for your kind words and your interest in sending a tip!

I'm currently part of Apple's "Small Business Program", so it's just a 15% cut for Apple and I get to keep 85% of tips. Because it's so convenient for users to use in-app tipping, I think it's an okay-ish ratio.

But I also just now set up a [GitHub Sponsors page](https://github.com/sponsors/johannes-schliephake), so everyone can decide if they want to send a tip that way. GitHub doesn't take any cuts, so I get 100% of the tip.
