### ISSUE TITLE
E2E with Fingerprint

### ISSUE THREAD

**Issue by Samurai1201** [johannes-schliephake/nextcloud-passwords-ios#68]
I would really love a feature, where similar to other Password Apps like LastPass, when using auto-Fill a login via Fingerprint or Face-ID is sufficient and when opening the App normally the full E2E Password has to be entered.

**Comment by johannes-schliephake** [comment]
For clarification: Does LastPass offer you to also view/edit other passwords or will it just fill in the matching password?

I'm asking because viewing and editing all passwords via auto-fill just with biometric auth (while the full app requires the E2E password) contradicts the core security measures of how this app implements E2E.

**Comment by Samurai1201** [comment]
It just displays the possible autofills like apples implementation does and lets you choose. But you dont have the ability to edit

**Comment by Samurai1201** [comment]
But to be honest, after using your app for a little bit, I like your implementation a lot more than Lastpass, so theres not really a need to change anything from my standpoint.
Thanks for your work, really love the app

**Comment by johannes-schliephake** [comment]
Thanks for your kind feedback!

It sounds like this way of implementing auto-fill wouldn't work for this app. I want to explore similar ideas in the future, i.e. QuickType for selecting a matching password directly from the keyboard, but this again might only be possible after authenticating the same way as with the full app.
